### PR TITLE
Feat/workshop

### PR DESCRIPTION
**Pull request by rikturr**
Workshop contents

### CODE REVIEW

**Comment by skirmer** [comment]
Only thing I still notice is that the "slow example" gridsearch in notebook 2 still segfaults for me when the n_jobs is -1. If I set n_jobs to 1 it works, and is slow per the expectation. Just something to keep in mind there.

**Comment by skirmer** [comment]
Fit exercise at the end of Notebook 4, before xgboost, takes a pretty long time to run on the cluster and might be a blocker for proceeding on to xgb. Maybe not a big deal but something to be aware of.

**Comment by skirmer** [comment]
Also about the end of notebook 4- when loading dask-xgboost I got a weird error `ImportError: libcuda.so.1: cannot open shared object file: No such file or directory`

**Review by skirmer — APPROVED** [review]
Recommend removing XGBoost section from Notebook 4 for this workshop, and be on guard for unexpected error in that gridsearch in Notebook 2- otherwise good to go.

**Comment by rikturr** [comment]
> Fit exercise at the end of Notebook 4, before xgboost, takes a pretty long time to run on the cluster and might be a blocker for proceeding on to xgb. Maybe not a big deal but something to be aware of.

I think this is okay because its the last parts of the notebook and attendees can continue running it after the workshop. 

All other issues we found were related to using wrong image, so this is good to go!

**Pull request merged**
